[package]
name = "tcod"
description = "The Rust bindings for the Doryen library (a.k.a. libtcod)."
version = "0.6.0"
homepage = "https://github.com/tomassedovic/tcod-rs"
repository = "https://github.com/tomassedovic/tcod-rs"
documentation = "http://tomassedovic.github.io/tcod-rs/tcod/index.html"
readme = "README.md"
keywords = ["gamedev", "roguelike", "libtcod"]
license = "WTFPL"
authors = ["Tomas Sedovic <tomas@sedovic.cz>",
           "Bastien Léonard <bastien.leonard@gmail.com>",
           "Darren Kaste <darrenkaste@gmail.com>",
           "Edu Garcia <arcnorj@gmail.com>",
           "Guillermo Galizzi <galizzi.guillermo@gmail.com>",
           "Gustorn <gustorn@gmail.com>",
           "Jared McFarland <jared.online@gmail.com>",
           "Jonny Gilchrist (@jgilchrist)",
           "LaylConway <laylconway@live.com>",
           "Moredread <code@andre-bubel.de>",
           "Nikita Pekin <contact@nikitapek.in>",
           "Paul Sanford <me@paulsanford.net>",
           "Pranz <jesper.fridefors@gmail.com>"]

[lib]
name = "tcod"
path = "src/lib.rs"

# Workaround for cargo test giving linker errors for doctests
doctest = false

[dependencies]
bitflags = "0.1"
libc = "0.1.5"
time = "0.1.25"

[dependencies.tcod-sys]
path = "tcod_sys"
version = "2.0.11"

[dev-dependencies]
rand = "0.3.8"
